name: lint

on:
  push:
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.js'
      - '**.jsx'
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: npm ci
    - run: npm run lint