on:
  push:
    branches:
      - master
    paths-ignore:
      #- '.github/**/*.yml'
      - '.gitignore'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise git describe --tags will not work
      - run: echo "previous_tag=$(git describe --tags --abbrev=0 || echo '')" >> $GITHUB_ENV
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        if: env.previous_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.create_tag.outputs.successful
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jeanouina|imalfect|dependabot\[bot\])
          filter: (^[\s]+?[R|r]elease)|(^[R|r]elease)
      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        if: steps.create_tag.outputs.successful
        with:
          version: ${{steps.create_tag.outputs.version}}
          release: true
          body: |
            ```bash
            npm i web3-vite@${{steps.create_tag.outputs.versionNumber}}
            ```

            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}

  npm-publish:
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Publish
        run: |
          npm ci
          node fix_vitejs
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github-publish:
    needs: tag
    runs-on: ubuntu-latest
    if: false # Temporary disabled, script does not work
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish
        run: |
          npm ci
          node fix_vitejs.js
          npm run build
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          npm publish --registry "https://npm.pkg.github.com"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}