on:
  push:
    branches:
      - master
    paths-ignore:
      #- '.github/**/*.yml'
      - '.gitignore'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise git describe --tags will not work
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: echo "previous_tag=$(git describe --tags --abbrev=0 || echo '')" >> $GITHUB_ENV
      - run: echo $previous_tag
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        if: env.previous_tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
      - name: Generate Changelog
        uses: jaywcjlove/create-tag-action@main
        if: steps.create_tag.outputs.successful
        with:
          version: ${{steps.create_tag.outputs.version}}
          release: true
          body: |
            ```bash
            npm i web3-vite@${{steps.create_tag.outputs.versionNumber}}
            ```

            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
      - name: Publish
        if: steps.create_tag.outputs.successful
        run: |
          npm ci
          node fix_vitejs
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish GitHub Package
        if: steps.create_tag.outputs.successful
        run: |
          npm publish --registry=https://npm.pkg.github.com 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}